"""Price-time-priority matching for incoming orders."""

from collections.abc import Callable
from datetime import datetime
from decimal import Decimal

from l3sim.domain.enums import OrderType, Side
from l3sim.domain.exceptions import InvalidOrderError
from l3sim.domain.order import Order
from l3sim.domain.order_book import OrderBook
from l3sim.domain.trade import Trade


class MatchingEngine:
    """Match incoming orders against an :class:`~l3sim.domain.OrderBook`.

    The engine selects the best opposing price and then the oldest resting
    order at that price.  Executions always occur at the resting order's
    price.  Residual limit quantity rests in the book; residual market
    quantity is cancelled (and therefore never rests).
    """

    __slots__ = ("_book", "_trade_id_factory", "_next_trade_id", "_trades")

    def __init__(
        self,
        book: OrderBook | None = None,
        *,
        trade_id_factory: Callable[[int], str | int] | None = None,
    ) -> None:
        self._book = book if book is not None else OrderBook()
        self._trade_id_factory = trade_id_factory or (lambda sequence: sequence)
        self._next_trade_id = 1
        self._trades: list[Trade] = []

    @property
    def book(self) -> OrderBook:
        """The engine's live order book."""

        return self._book

    @property
    def trades(self) -> tuple[Trade, ...]:
        """All trades generated by this engine, in execution order."""

        return tuple(self._trades)

    def submit(self, order: Order) -> tuple[Trade, ...]:
        """Match an incoming order and return trades generated by it.

        An incoming limit order that cannot fully execute rests with its
        remaining quantity. Market orders never rest.
        """

        if not isinstance(order, Order):
            raise InvalidOrderError("matching engine can process only Order instances")
        if self._book.get_order(order.order_id) is not None:
            raise InvalidOrderError(f"duplicate active order ID: {order.order_id!r}")
        if order.is_filled:
            raise InvalidOrderError("filled orders cannot be submitted")

        remaining = order.remaining_quantity
        generated: list[Trade] = []
        while remaining > 0:
            resting = self._next_match(order)
            if resting is None:
                break

            quantity = min(remaining, resting.remaining_quantity)
            trade = self._create_trade(order, resting, quantity)
            generated.append(trade)
            self._trades.append(trade)
            remaining -= quantity
            self._update_resting_order(resting, quantity)

        if remaining and order.order_type is OrderType.LIMIT:
            self._book.add_order(order.with_remaining(remaining))
        return tuple(generated)

    def process_market_order(self, order: Order) -> tuple[Trade, ...]:
        """Process a market order; provided as a descriptive API alias."""

        if not isinstance(order, Order) or order.order_type is not OrderType.MARKET:
            raise InvalidOrderError("process_market_order requires a market order")
        return self.submit(order)

    def cancel(self, order_id: str | int, quantity: int | None = None) -> Order:
        """Cancel all or part of an active resting order.

        ``quantity`` is an amount to cancel, rather than the desired remaining
        quantity.  Omitting it removes the order entirely.  A partial cancel
        retains the order's position in its price-level FIFO queue.
        """

        order = self._active_order(order_id)
        if quantity is None:
            cancelled = self._book.remove_order(order_id)
            assert cancelled is not None  # guaranteed by _active_order
            return cancelled

        self._validate_quantity(quantity, "cancel quantity")
        if quantity > order.remaining_quantity:
            raise InvalidOrderError("cancel quantity cannot exceed remaining quantity")
        if quantity == order.remaining_quantity:
            cancelled = self._book.remove_order(order_id)
            assert cancelled is not None
            return cancelled

        updated = order.with_remaining(order.remaining_quantity - quantity)
        self._book.replace_order(updated)
        return updated

    def modify(
        self,
        order_id: str | int,
        *,
        price: Decimal | None = None,
        quantity: int | None = None,
    ) -> tuple[Trade, ...]:
        """Modify an active order and return trades caused by the change.

        ``quantity`` is the desired *remaining* quantity.  Reducing it at the
        same price preserves FIFO priority.  Increasing it, or changing price,
        is implemented as cancel/re-submit, so the order moves to the back of
        the queue.  A price change can therefore execute immediately.
        """

        if price is None and quantity is None:
            raise InvalidOrderError("a modification must include a price or quantity")
        if price is not None and (not isinstance(price, Decimal) or price <= 0):
            raise InvalidOrderError("modified price must be a positive Decimal")
        if quantity is not None:
            self._validate_quantity(quantity, "modified quantity")

        order = self._active_order(order_id)
        new_price = order.price if price is None else price
        new_remaining = order.remaining_quantity if quantity is None else quantity
        assert new_price is not None

        price_changed = new_price != order.price
        quantity_increased = new_remaining > order.remaining_quantity
        if not price_changed and not quantity_increased:
            if new_remaining == order.remaining_quantity:
                return ()
            updated = order.with_remaining(new_remaining)
            self._book.replace_order(updated)
            return ()

        # This is a new submission for queue-priority purposes, so its total
        # quantity starts at the requested outstanding quantity.
        replacement = Order(
            order_id=order.order_id,
            timestamp=order.timestamp,
            side=order.side,
            price=new_price,
            quantity=new_remaining,
            remaining_quantity=new_remaining,
        )
        self._book.remove_order(order_id)
        return self.submit(replacement)

    def _next_match(self, incoming: Order) -> Order | None:
        price = self._book.best_ask() if incoming.side is Side.BUY else self._book.best_bid()
        if price is None:
            return None
        if incoming.order_type is OrderType.LIMIT:
            if incoming.price is None:
                raise InvalidOrderError("limit order must have a price")
            if incoming.side is Side.BUY and incoming.price < price:
                return None
            if incoming.side is Side.SELL and incoming.price > price:
                return None

        resting_side = Side.SELL if incoming.side is Side.BUY else Side.BUY
        level = self._book.get_price_level(resting_side, price)
        if level is None:
            raise InvalidOrderError("best price has no corresponding price level")
        return level.oldest_order()

    def _create_trade(self, incoming: Order, resting: Order, quantity: int) -> Trade:
        buy_order_id, sell_order_id = (
            (incoming.order_id, resting.order_id)
            if incoming.side is Side.BUY
            else (resting.order_id, incoming.order_id)
        )
        trade = Trade(
            trade_id=self._trade_id_factory(self._next_trade_id),
            timestamp=incoming.timestamp,
            buy_order_id=buy_order_id,
            sell_order_id=sell_order_id,
            price=self._resting_price(resting),
            quantity=quantity,
        )
        self._next_trade_id += 1
        return trade

    def _update_resting_order(self, resting: Order, filled_quantity: int) -> None:
        remaining = resting.remaining_quantity - filled_quantity
        if remaining == 0:
            self._book.remove_order(resting.order_id)
        else:
            self._book.replace_order(resting.with_remaining(remaining))

    def _active_order(self, order_id: str | int) -> Order:
        order = self._book.get_order(order_id)
        if order is None:
            raise InvalidOrderError(f"order ID is not present in book: {order_id!r}")
        return order

    @staticmethod
    def _validate_quantity(quantity: int, label: str) -> None:
        if not isinstance(quantity, int) or isinstance(quantity, bool) or quantity <= 0:
            raise InvalidOrderError(f"{label} must be a positive integer")

    @staticmethod
    def _resting_price(order: Order) -> Decimal:
        if order.price is None:
            raise InvalidOrderError("resting order must have a limit price")
        return order.price
